## Configuracion del cliente de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: book-service


## Configuracion de Instancia
server:
  port: 8082
  error:
    include-stacktrace: on_param

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

