## Configuracion del cliente de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue


## Configuracion de Instancia
server:
  port: 8082
  error:
    include-stacktrace: on_param

spring:
  application:
    name: ms-books-catalogue
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

