## Configuracion del cliente de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue


## Configuracion de Instancia
server:
  port: 8088
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

spring:
  application:
    name: ms-books-catalogue

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
logging:
  level:
    tracer: TRACE

